name: CI/CD Pipeline

on:
  push:
    branches:
      - Dev1
      - SIT
      - UAT
  pull_request:
    branches:
      - SIT

jobs:
  build-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.20.3'

    - name: Install Salesforce CLI
      run: npm install --global @salesforce/cli

    - name: Set up Salesforce environment variables
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SERVERURL: ${{ secrets.SF_SERVERURL }}
      run: echo "Salesforce environment variables set."

    - name: Deploy to Salesforce
      run: |
        echo "Deploying to Salesforce..."
        ant -lib lib/ant-salesforce.jar deploy
